run:
  timeout: 5m
  go: "1.22"
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/gustavotesin/go-job-scheduler
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id
  misspell:
    locale: US
  gosec:
    excludes:
      - G104 # audited elsewhere via errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
        - errcheck
    - path: cmd/
      linters:
        - gocyclo

output:
  sort-results: true
